{% set name = "localstack-plugin-loader" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/localstack-plugin-loader-{{ version }}.tar.gz
  sha256: eb829c47332caf2ff1062a2038077e0a5e93c30bb2c61cf2651b07ccadd77448

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - stevedore >=3.4

test:
  imports:
    - plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/localstack/localstack-plugin-loader
  summary: The dynamic code loading framework used in LocalStack
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - admax18
